/* ================= RYSUNKI GATUNKÓW =================
   id gatunku → [archetyp lub preset z art.js, opcje]. p = indeks palety PAL.
   Sobowtóry różnią się kształtem, nie tylko kolorem (sylwetka to podpowiedź dla nieodkrytych). */
const ART = {
  /* tyranozaury: wielka głębokie głowa, maleńkie rączki */
  'tyrannosaurus-rex': ['thero', { p: 6, hd: 'rex', nk: [20, -24], nw: 28, bw: 37, bh: 26, arm: 6, clw: 2, cl: 3, lw: 26, tw: 30, sc: 1.06 }],
  'tarbosaurus-bataar': ['thero', { p: 11, hs: [42, 24, .84, 0], nk: [22, -26], nw: 25, bw: 35, bh: 24, arm: 6, clw: 2, cl: 3, lw: 24 }],
  'albertosaurus-sarcophagus': ['thero', { p: 12, hd: 'tyr', brow: 1, nk: [24, -28], bw: 31, bh: 20, arm: 7, clw: 2, cl: 3, lg: 1.12, lw: 20 }],
  'daspletosaurus-torosus': ['thero', { p: 16, hs: [40, 27, .88, 0], brow: 1, nk: [20, -26], nw: 26, bw: 35, bh: 24, arm: 7, clw: 2, cl: 3, lw: 24 }],
  'yutyrannus-huali': ['thero', { p: 3, hd: 'tyr', fz: 1, ncr: 1, arm: 11, clw: 3, cl: 5, bw: 32, bh: 21 }],
  /* karcharodontozaury: długa niska głowa, długi tułów, 3 palce */
  'giganotosaurus-carolinii': ['thero', { p: 2, hd: 'long', brow: 1, nk: [30, -20], nw: 22, bw: 41, bh: 21, tl: 1.2, td: 10, arm: 12, clw: 3, cl: 5, sc: 1.06 }],
  'carcharodontosaurus-saharicus': ['thero', { p: 8, hs: [50, 25, .74, 0], bt: 1, nk: [28, -22], bw: 38, bh: 22, tl: 1.1, arm: 11, clw: 3, cl: 5 }],
  /* spinozaury: pysk krokodyla */
  'spinosaurus-aegyptiacus': ['thero', { p: 10, sail: 1, hd: 'croc', nk: [28, -30], nw: 18, lg: .8, bw: 36, bh: 21, arm: 14, clw: 3, cl: 6, tl: 1.2, td: 6 }],
  'baryonyx-walkeri': ['thero', { p: 12, hs: [46, 15, .32, 0], nk: [28, -26], nw: 18, arm: 15, clw: 1, cl: 13, bw: 32, bh: 20 }],
  'suchomimus-tenerensis': ['thero', { p: 11, hd: 'croc', rdg: 1, nk: [28, -26], nw: 18, arm: 14, clw: 2, cl: 8 }],
  /* allozaury: rożki nad oczami, długie ręce z 3 pazurami */
  'allosaurus-fragilis': ['thero', { p: 13, hd: 'allo', hrn: 1, nk: [26, -32], nw: 20, bw: 31, bh: 20, arm: 17, clw: 3, cl: 7, lg: 1.05 }],
  'acrocanthosaurus-atokensis': ['thero', { p: 7, hd: 'allo', rdg: 1, bw: 34, bh: 22, arm: 13, clw: 3, cl: 6 }],
  'torvosaurus-tanneri': ['thero', { p: 5, hs: [46, 22, .72, 0], bw: 36, bh: 24, arm: 9, clw: 3, cl: 5, lw: 24 }],
  'megalosaurus-bucklandii': ['thero', { p: 15, hs: [40, 19, .65, 0], arm: 12, clw: 3, cl: 5 }],
  /* ozdoby głowy */
  'ceratosaurus-nasicornis': ['thero', { p: 12, hd: 'allo', nose: 1, hrn: 1, osteo: 1, arm: 9, clw: 3, cl: 4 }],
  'dilophosaurus-wetherilli': ['thero', { p: 1, cr2: 1, hd: 'slim', nk: [26, -32], nw: 17, bw: 29, bh: 19, arm: 12, clw: 3, cl: 5, sc: .95 }],
  'cryolophosaurus-ellioti': ['thero', { p: 4, cryo: 1, hs: [34, 17, .55, 0], arm: 12, clw: 3, cl: 5 }],
  'carnotaurus-sastrei': ['thero', { p: 7, hd: 'short', bull: 1, arm: 4, lg: 1.15, bw: 31, bh: 20, lw: 20, nk: [24, -28], tw: 22 }],
  'majungasaurus-crenatissimus': ['thero', { p: 13, hs: [30, 22, .8, 0], boss: 1, arm: 4, bw: 32, bh: 22, lw: 22 }],
  'herrerasaurus-ischigualastensis': ['thero', { p: 11, hd: 'slim', nk: [26, -26], nw: 16, bw: 26, bh: 17, lw: 16, arm: 12, clw: 3, cl: 5, tl: 1.1, sc: .85 }],
  /* małe drapieżniki */
  'coelophysis-bauri': ['thero', { p: 3, hs: [30, 11, .4, 0], nk: [26, -38], nw: 11, bw: 24, bh: 14, lw: 14, lg: 1.15, arm: 12, clw: 3, cl: 4, tl: 1.2, sc: .8 }],
  'eoraptor-lunensis': ['thero', { p: 13, hs: [20, 13, .5, 0], nk: [20, -26], nw: 12, bw: 22, bh: 15, lw: 14, arm: 10, clw: 3, cl: 4, sc: .6 }],
  'compsognathus-longipes': ['thero', { p: 8, hd: 'small', nk: [20, -28], nw: 10, bw: 20, bh: 13, lw: 12, lg: 1.1, arm: 8, clw: 2, cl: 3, tl: 1.1, td: 6, sc: .55 }],
  /* raptory: pióra, sierpowy pazur, sztywny ogon */
  'velociraptor-mongoliensis': ['raptor', { p: 3, sc: .8 }],
  'deinonychus-antirrhopus': ['raptor', { p: 4, hs: [32, 15, .5, 0], bw: 29, bh: 18, lw: 19, sc: .95 }],
  'utahraptor-ostrommaysorum': ['raptor', { p: 7, hs: [36, 18, .55, 0], bw: 34, bh: 22, lw: 23, nw: 18, lg: 1, sc: 1.05 }],
  'troodon-formosus': ['raptor', { p: 12, hs: [26, 14, .4, 0], ey: 1.35, lg: 1.2, sc: .8 }],
  'microraptor-gui': ['bird', { p: 14, four: 1 }],
  'archaeopteryx-lithographica': ['bird', { p: 8 }],
  'sinosauropteryx-prima': ['thero', { p: 16, hd: 'small', fz: 1, tstr: 1, tl: 1.3, td: 4, nk: [20, -26], nw: 10, bw: 20, bh: 13, lw: 12, arm: 8, clw: 2, cl: 3, sc: .6 }],
  'mononykus-olecranus': ['thero', { p: 3, hd: 'tiny', fz: 1, lg: 1.5, nk: [18, -40], nw: 10, bw: 20, bh: 14, lw: 12, arm: 5, aw: 6, clw: 1, cl: 6, td: 2, sc: .65 }],
  'oviraptor-philoceratops': ['thero', { p: 5, hd: 'ovi', bk: .7, cr: 'helm', fz: 1, wg: 1, arm: 12, clw: 3, cl: 4, vane: [.5, 8], nk: [18, -34], nw: 12, bw: 24, bh: 17, lw: 15, lg: 1.2, sc: .75 }],
  /* strusiopodobne */
  'gallimimus-bullatus': ['ornimim', { p: 9 }],
  'struthiomimus-altus': ['ornimim', { p: 3, sc: .9 }],
  'ornithomimus-velox': ['ornimim', { p: 13, fz: 1, wg: 1, sc: .85 }],
  'deinocheirus-mirificus': ['thero', { p: 16, hd: 'deino', bk: .5, hump: 1, ak: 'fwd', arm: 26, clw: 3, cl: 12, nk: [22, -40], nw: 14, lg: 1.2, bw: 36, bh: 26, fz: 1, td: 8 }],
  'therizinosaurus-cheloniformis': ['thero', { p: 6, hd: 'tiny', bk: .5, fz: 1, ak: 'fwd', arm: 26, clw: 3, cl: 26, aw: 10, nk: [16, -40], nw: 14, bw: 34, bh: 28, rot: -18, tl: .5, td: 4, lg: 1.1 }],
  'smok-wawelski': ['dragon', { p: 0, bw: 34 }],
  /* prozauropody */
  'plateosaurus-engelhardti': ['prosauro', { p: 3 }],
  'massospondylus-carinatus': ['prosauro', { p: 12, nk: [28, -42], sc: .85 }],
  /* zauropody: sylwetka szyi i ogona niesie tożsamość */
  'mamenchisaurus-sinocanadorum': ['sauro', { p: 8, na: 40, nl: 125, nc: 12, nw: 20, bw: 36, bh: 22, tl: .9 }],
  'brachiosaurus-altithorax': ['sauro', { p: 11, fl: 54, hl: 38, na: 74, nl: 80, nc: -4, nw: 24, hd: 'brach', tl: .7 }],
  'diplodocus-carnegii': ['sauro', { p: 12, na: 12, nl: 80, nc: 6, nw: 18, whip: 1, hd: 'long', tl: 1.3, bw: 40, bh: 22 }],
  'apatosaurus-louisae': ['sauro', { p: 6, na: 26, nl: 66, nw: 32, bw: 44, bh: 28, lw: 24 }],
  'brontosaurus-excelsus': ['sauro', { p: 15, na: 34, nl: 66, nw: 30, bw: 42, bh: 27, lw: 22 }],
  'camarasaurus-supremus': ['sauro', { p: 3, na: 48, nl: 50, nw: 26, hd: 'box', fl: 40 }],
  'europasaurus-holgeri': ['sauro', { p: 13, fl: 44, hl: 36, na: 60, nl: 56, hd: 'brach', sc: .65 }],
  'amargasaurus-cazaui': ['sauro', { p: 5, spn: 1, na: 20, nl: 52, nw: 18, bw: 36, bh: 23, fl: 34 }],
  'nigersaurus-taqueti': ['sauro', { p: 4, hd: 'mower', na: -5, nl: 46, nc: -14, ha: 62, nw: 18, bw: 36, bh: 22, sc: .9 }],
  'saltasaurus-loricatus': ['sauro', { p: 2, arm2: 1, na: 30, nl: 52, bw: 38, sc: .85 }],
  'alamosaurus-sanjuanensis': ['sauro', { p: 16, na: 36, nl: 74, nw: 28, bw: 46, bh: 29, lw: 24 }],
  'argentinosaurus-huinculensis': ['sauro', { p: 9, na: 30, nl: 80, nw: 30, bw: 50, bh: 32, lw: 26, fl: 42 }],
  'patagotitan-mayorum': ['sauro', { p: 14, na: 42, nl: 84, nw: 28, bw: 48, bh: 30, lw: 26, fl: 44 }],
  'dreadnoughtus-schrani': ['sauro', { p: 20, na: 24, nl: 70, nw: 32, bw: 48, bh: 32, lw: 28, tl: 1.1 }],
  /* ceratopsy: kryza i rogi */
  'psittacosaurus-mongoliensis': ['orni', { p: 15, hd: 'parrot', bk: .6, cheek: 1, brist: 1, nk: [18, -20], nw: 15, bw: 24, bh: 17, lw: 16, arm: 10, sc: .78 }],
  'protoceratops-andrewsi': ['cerat', { p: 3, fr: 'plain', nose: 0, brow: 0, boss: 1, sc: .75 }],
  'triceratops-horridus': ['cerat', { p: 7, fr: 'round', brow: [34, -40], nose: 12 }],
  'torosaurus-latus': ['cerat', { p: 11, fr: 'huge', win: 1, brow: [34, -45], nose: 10 }],
  'styracosaurus-albertensis': ['cerat', { p: 2, fr: 'spiky', nose: 30, brow: 0 }],
  'centrosaurus-apertus': ['cerat', { p: 12, fr: 'hook', nose: 24, brow: 0 }],
  'pachyrhinosaurus-canadensis': ['cerat', { p: 16, fr: 'round', fspk: 1, boss: 1, nose: 0, brow: 0 }],
  'chasmosaurus-belli': ['cerat', { p: 6, fr: 'tall', win: 1, brow: [12, -60], nose: 8 }],
  'pentaceratops-sternbergii': ['cerat', { p: 5, fr: 'huge', brow: [32, -50], nose: 12, cheek: 1 }],
  'kosmoceratops-richardsoni': ['cerat', { p: 13, fr: 'curly', brow: [22, 10], nose: 8 }],
  'sinoceratops-zhuchengensis': ['cerat', { p: 8, fr: 'ring', nose: 18, brow: 0 }],
  /* stegozaury */
  'stegosaurus-stenops': ['stego', { p: 15, n: 9, ts: 4, ph: 1.2 }],
  'kentrosaurus-aethiopicus': ['stego', { p: 2, n: 7, pl: 'spike', ts: 6, shd: 1 }],
  'miragaia-longicollum': ['stego', { p: 1, n: 10, nk: 1, ph: .8 }],
  /* ankylozaury */
  'ankylosaurus-magniventris': ['armor', { p: 12, club: 1, spk: 1 }],
  'euoplocephalus-tutus': ['armor', { p: 6, club: 1, spk: 0 }],
  'nodosaurus-textilis': ['armor', { p: 11, club: 0, spk: 1 }],
  'edmontonia-rugosidens': ['armor', { p: 3, club: 0, shd: 1, spk: 1 }],
  /* ornitopody (bez kaczego dzioba) */
  'heterodontosaurus-tucki': ['orni', { p: 8, hd: 'small', bk: .3, tusk: 1, brist: 1, nk: [18, -22], nw: 11, bw: 20, bh: 14, lw: 13, lg: 1.1, arm: 9, sc: .55 }],
  'hypsilophodon-foxii': ['orni', { p: 15, hd: 'small', bk: .35, lg: 1.25, bw: 22, bh: 15, lw: 14, nk: [20, -24], nw: 12, arm: 9, td: 2, sc: .65 }],
  'tenontosaurus-tilletti': ['orni', { p: 16, hs: [28, 16, .62, 1], q: 1, tl: 1.4, td: 12, bw: 34, bh: 22, nk: [24, -16] }],
  'iguanodon-bernissartensis': ['orni', { p: 4, thumb: 2, bw: 36, bh: 24, lw: 24, arm: 14 }],
  'ouranosaurus-nigeriensis': ['orni', { p: 8, sail: 1, cr: 'bump', q: 1, nk: [24, -18] }],
  /* kaczodziobe */
  'maiasaura-peeblesorum': ['hadro', { p: 11, cr: 'bump', q: 1, nk: [24, -14] }],
  'edmontosaurus-annectens': ['hadro', { p: 3, q: 1, bw: 38, bh: 24, nk: [24, -12] }],
  'parasaurolophus-walkeri': ['hadro', { p: 1, cr: 'tube' }],
  'corythosaurus-casuarius': ['hadro', { p: 5, cr: 'helm' }],
  'lambeosaurus-lambei': ['hadro', { p: 2, cr: 'hatch' }],
  'saurolophus-osborni': ['hadro', { p: 9, cr: 'spike' }],
  'shantungosaurus-giganteus': ['hadro', { p: 18, q: 1, bw: 42, bh: 27, lw: 26, nk: [24, -12], sc: 1.05 }],
  /* grubogłowe */
  'pachycephalosaurus-wyomingensis': ['dome', { p: 2, dm: 1.1 }],
  'stygimoloch-spinifer': ['dome', { p: 7, dm: .8, dspk: 1 }],
  'silesaurus-opolensis': ['orni', { p: 13, hd: 'small', bk: .3, q: 1, lg: 1.2, bw: 22, bh: 14, lw: 11, nk: [20, -18], nw: 10, tl: 1.2, td: 6, sc: .6 }],
  /* pterozaury */
  'dimorphodon-macronyx': ['ptero', { p: 2, bl: 26, hd: 22, tl: 1 }],
  'rhamphorhynchus-muensteri': ['ptero', { p: 12, bl: 34, hd: 11, tl: 1 }],
  'pterodactylus-antiquus': ['ptero', { p: 8, cr: 'small', bl: 34, hd: 11, sc: .8 }],
  'pteranodon-longiceps': ['ptero', { p: 4, cr: 'back', bk: 1, bl: 50 }],
  'nyctosaurus-gracilis': ['ptero', { p: 17, cr: 'mast', bk: 1, bl: 40 }],
  'tapejara-wellnhoferi': ['ptero', { p: 13, cr: 'sail', bk: 1, bl: 26, hd: 16 }],
  'tropeognathus-mesembrinus': ['ptero', { p: 10, cr: 'keel', bl: 44 }],
  'anhanguera-santanae': ['ptero', { p: 1, cr: 'keel', bl: 42, hd: 11 }],
  'quetzalcoatlus-northropi': ['ptero', { p: 11, stand: 1, bk: 1, cr: 'quetz', bl: 56, hd: 14 }],
  'hatzegopteryx-thambema': ['ptero', { p: 7, stand: 1, bk: 1, cr: 'quetz', bl: 44, hd: 22, nw: 17 }],
  /* gady morskie */
  'nothosaurus-mirabilis': ['plesio', { p: 12, nk: 'short', lg: 1 }],
  'plesiosaurus-dolichodeirus': ['plesio', { p: 10, nk: 'long' }],
  'elasmosaurus-platyurus': ['plesio', { p: 17, nk: 'xlong' }],
  'liopleurodon-ferox': ['mosa', { p: 4, plio: 1 }],
  'pliosaurus-funkei': ['mosa', { p: 9, plio: 1, sn: 6, bt: 1 }],
  'kronosaurus-queenslandicus': ['mosa', { p: 14, plio: 1 }],
  'ichthyosaurus-communis': ['ichthyo', { p: 9, sc: .8 }],
  'ophthalmosaurus-icenicus': ['ichthyo', { p: 17, ey: 1.8 }],
  'shonisaurus-popularis': ['ichthyo', { p: 4, nofin: 1 }],
  'mosasaurus-hoffmannii': ['mosa', { p: 17 }],
  'tylosaurus-proriger': ['mosa', { p: 10, sn: 6 }],
  'archelon-ischyros': ['turtle', { p: 12 }],
  /* ryby i wieloryby */
  'dunkleosteus-terrelli': ['fish', { p: 11 }],
  'helicoprion-bessonovi': ['fish', { p: 14, k: 'helico' }],
  'leedsichthys-problematicus': ['fish', { p: 10, k: 'leeds' }],
  'otodus-megalodon': ['shark', { p: 9 }],
  'livyatan-melvillei': ['whale', { p: 18 }],
  'basilosaurus-cetoides': ['whale', { p: 4, k: 'eel' }],
  /* krokodylomorfy i jaszczury */
  'postosuchus-kirkpatricki': ['croc', { p: 16, up: 1, sn: 30, hh: 1.3 }],
  'polonosuchus-silesiacus': ['croc', { p: 7, up: 1, sn: 32, hh: 1.25 }],
  'poposaurus-gracilis': ['thero', { p: 5, hd: 'slim', nk: [22, -20], nw: 14, bw: 28, bh: 15, lw: 15, arm: 7, clw: 2, cl: 3, tl: 1.4, td: 10, sc: .7 }],   // dwunożny pseudozuch: krótkie ręce, długi ogon
  'kaprosuchus-saharicus': ['croc', { p: 2, up: 1, tsk: 1, brow: 1, sc: .85 }],
  'sarcosuchus-imperator': ['croc', { p: 12, sn: 52, bulla: 1 }],
  'deinosuchus-riograndensis': ['croc', { p: 6, sn: 40, hh: 1.2, bt: 1 }],
  'purussaurus-brasiliensis': ['croc', { p: 11, sn: 44, hh: 1.3 }],
  'titanoboa-cerrejonensis': ['snake', { p: 15 }],
  'varanus-priscus': ['lizard', { p: 11 }],
  'tanystropheus-longobardicus': ['lizard', { p: 3, nkl: 56, up: 0 }],
  /* synapsydy */
  'dimetrodon-grandis': ['sail', { p: 7 }],
  'edaphosaurus-pogonias': ['sail', { p: 12, short: 1 }],
  'moschops-capensis': ['synap', { p: 11, hd: 'thick', sl: 12, up: 1 }],
  'inostrancevia-alexandri': ['synap', { p: 9, hd: 'gorgon', bw: 40 }],
  'lystrosaurus-murrayi': ['synap', { p: 3, sc: .7 }],
  'lisowicia-bojani': ['synap', { p: 16, up: 1, tl: 16, bw: 44 }],
  /* płazy */
  'eryops-megacephalus': ['amphib', { p: 6 }],
  'diplocaulus-magnicornis': ['amphib', { p: 1, boom: 1 }],
  'metoposaurus-krasiejowensis': ['amphib', { p: 12, flat: 1 }],
  /* bezkręgowce */
  'anomalocaris-canadensis': ['anomalo', { p: 21 }],
  'trilobita': ['bug', { p: 17 }],
  'ammonoidea': ['ammo', { p: 13 }],
  'jaekelopterus-rhenaniae': ['scorp', { p: 7 }],
  'meganeura-monyi': ['bug', { p: 12, k: 'dragon' }],
  'arthropleura-armata': ['bug', { p: 16, k: 'milli' }],
  /* ptaki terroru */
  'gastornis-giganteus': ['tbird', { p: 9, hd: 'gast', bk: .9, lg: 1.1, lw: 20, nk: [12, -34], nw: 20, bw: 30, bh: 24 }],
  'phorusrhacos-longissimus': ['tbird', { p: 19 }],
  /* ssaki */
  'andrewsarchus-mongoliensis': ['mammal', { p: 20, hd: 'andrew', tail: 'long', lh: 32, lw: 14, bw: 40, bh: 22, nk: [16, -6] }],
  'paraceratherium-transouralicum': ['mammal', { p: 18, hd: 'indri', lh: 52, lw: 15, bw: 40, bh: 24, nk: [22, -40], nw: 20, ft: 'hoof', tail: 'short' }],
  'deinotherium-giganteum': ['ele', { p: 9, tu: 'down', hump: 0 }],
  'mammuthus-primigenius': ['ele', { p: 20, fur: 1, tu: 'up' }],
  'coelodonta-antiquitatis': ['mammal', { p: 11, hd: 'rhino', fur: 1, hump: 1, lh: 24, lw: 15, bw: 42, bh: 24, ft: 'hoof', nk: [16, 4], tail: 'short' }],
  'megaloceros-giganteus': ['mammal', { p: 16, hd: 'deer', lh: 44, lw: 9, bw: 36, bh: 18, ft: 'hoof', hock: 1, nk: [20, -26], nw: 16, hump: 1, tail: 'short' }],
  'ursus-spelaeus': ['mammal', { p: 20, hd: 'bear', lh: 28, lw: 17, bw: 42, bh: 26, hump: 1, fur: 1, tail: 'none' }],
  'panthera-spelaea': ['cat', { p: 19, lh: 34, bw: 40, bh: 18 }],
  'smilodon-fatalis': ['cat', { p: 3, sab: 1, tail: 'short', lh: 30, lw: 14, bw: 36, bh: 20, hump: 1 }],
  'aenocyon-dirus': ['mammal', { p: 9, hd: 'dog', tail: 'bush', hock: 1, lh: 34, lw: 11, bw: 34, bh: 17, nk: [20, -12] }],
  'megatherium-americanum': ['sloth', { p: 11 }],
  'glyptodon-clavipes': ['armor', { p: 16, glyp: 1, club: 0, spk: 0 }],
  'diprotodon-optatum': ['mammal', { p: 11, hd: 'diproto', lh: 26, lw: 18, bw: 44, bh: 26, tail: 'none' }],
};
if (typeof module !== 'undefined') module.exports = { ART };
